"""Updated Alarm model

Revision ID: 5c2c248b5c58
Revises: 193159329495
Create Date: 2026-04-16 11:54:51.916175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2c248b5c58'
down_revision = '193159329495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('light', sa.Integer(), nullable=True),
    sa.Column('sound', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('motion', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('goal_percent', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=30), nullable=True))
        batch_op.alter_column('repeat_days',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.drop_column('smart_wakeup_window')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('serial_number',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smart_wakeup_window', sa.INTEGER(), nullable=True))
        batch_op.alter_column('repeat_days',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('label')

    op.drop_table('user_goals')
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
